name: CI/CD

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Instalar dependências
        run: npm ci

      - name: Executar ESLint
        run: npm run lint

      - name: Executar testes
        run: npm test -- --runInBand

      - name: Gerar build
        run: npm run build

  deploy:
    needs: ci

    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - run: npm ci

      - name: Instalar Vercel CLI
        run: npm install -g vercel

      - name: Deploy na Vercel
        run: vercel --prod --token=${{ secrets.VERCEL_TOKEN }}